### ISSUE TITLE
Nodes State entry not removed after Scaledown ()

### ISSUE THREAD

**Issue by Abhishek1121-tech** [Orange-OpenSource/nifikop#110]
## Bug Report

**What did you do?**
Scaledown : Gracefully remove node

<img width="448" alt="Screenshot 2021-06-14 at 4 28 47 PM" src="https://user-images.githubusercontent.com/62426428/121882244-edb1b180-cd2d-11eb-9a96-948c1e9e0987.png">

**What did you expect to see?**
The entry in Status for node is to be removed.

**What did you see instead? Under which circumstances?**
Entry exist with state POD_REMOVING, as pod is already removed and no pod running.

<img width="758" alt="Screenshot 2021-06-14 at 4 15 00 PM" src="https://user-images.githubusercontent.com/62426428/121882548-500ab200-cd2e-11eb-9a7d-3e83c7aa63ed.png">

**Environment**

* nifikop version: 0.6.0

* go version: go1.13.15

* Kubernetes version information: v1.18.14

* Kubernetes cluster kind: 

* NiFi version: 1.12.1

**Comment by erdrix** [comment]
Linked to #131
