### ISSUE TITLE
metrics port mismatch 

### ISSUE THREAD

**Issue by riccardo-salamanna** [Orange-OpenSource/nifikop#145]
## Bug Report

**What did you do?**
I noticed that nifikop is exposing metrics via port 8080 from the go code, but the port is not exposed in the deployment and the service `-metrics` is pointing to port 9710. I wonder if that is a bug or if i am misunderstanding something :) thanks

**What did you expect to see?**
I suspect the service should point to port 8080 and it should be exposed to allow prometheus to scrape for metrics.

**What did you see instead? Under which circumstances?**
Connections is refused by the service :) 

**Environment**
* nifikop version: 0.7.0

* Kubernetes version information: 1.19

* Kubernetes cluster kind: EKS

* NiFi version: 1.13.2

**Possible Solution**
either change the port for metrics in the go code or in the service i suppose? again, if i am not misunderstanding something

**Comment by michael81877** [comment]
It would depend on your `NiFiCluster.spec.listenersConfig.internalListeners` "prometheus" port. This is the port nifikop configures the `PrometheusReportingTask` to expose metrics on.

I've confirmed this by successfully scraping NiFi metrics into Prometheus and the code also does this here:

https://github.com/Orange-OpenSource/nifikop/blob/master/api/v1alpha1/nificluster_types.go#L663-L673

**Comment by erdrix** [comment]
I think what we are talking about here is the metric port of the operator, not the one for NiFi nodes cluster (that expose metric using the reporting task).
And you are right the default port is  8080: https://github.com/Orange-OpenSource/nifikop/blob/master/main.go#L68
And the service is configured on 9710 : https://github.com/Orange-OpenSource/nifikop/blob/master/helm/nifikop/templates/service.yaml#L17

**Comment by riccardo-salamanna** [comment]
> I think what we are talking about here is the metric port of the operator, not the one for NiFi nodes cluster (that expose metric using the reporting task). And you are right the default port is 8080: https://github.com/Orange-OpenSource/nifikop/blob/master/main.go#L68 And the service is configured on 9710 : https://github.com/Orange-OpenSource/nifikop/blob/master/helm/nifikop/templates/service.yaml#L17

preciseley! thank you very much

**Comment by riccardo-salamanna** [comment]
Hi @erdrix - i was verifying your change and altough you now allowed to specify the port for the metrics in the values, port 8080 that exposes prometheus metrics for the nifikop operator is not declared in the deployment. I manually edited the value on our setup with:
```          ports:
          - containerPort: 8080
            protocol: TCP
```
since the port is hardcoded in the main.go i did not felt the need to add it as a parameter.  I also added a target port to the metrics ingress definition:
```
  - name: metrics
    port: {{ .Values.metrics.port }}
    protocol: TCP
    targetPort: 8080
```
Could you maybe add it to next release or a similar fix, thanks :) and keep up with the amazing work
