### ISSUE TITLE
metric issue - follow from #145

### ISSUE THREAD

**Issue by riccardo-salamanna** [Orange-OpenSource/nifikop#171]
https://github.com/Orange-OpenSource/nifikop/issues/145#issue-1038541455

Hi @erdrix - i was verifying your change and altough you now allowed to specify the port for the metrics in the values, port 8080 that exposes prometheus metrics for the nifikop operator is not declared in the deployment. I manually edited the value on our setup with:
```
          - containerPort: 8080
            protocol: TCP
```
since the port is hardcoded in the main.go i did not felt the need to add it as a parameter. I also added a target port to the metrics ingress definition:
```
  - name: metrics
    port: {{ .Values.metrics.port }}
    protocol: TCP
    targetPort: 8080
```
Could you maybe add it to next release or a similar fix, thanks :) and keep up with the amazing work

**Comment by michael81877** [comment]
Raised #172
