### ISSUE TITLE
[BUG] PVCs/PVs for one pod are created in different zones

### ISSUE THREAD

**Issue by xvzf** [Orange-OpenSource/nifikop#73]
## Bug Report

**What did you do?**
Create the sample cluster

**What did you expect to see?**
Cluster nodes going up

**What did you see instead? Under which circumstances?**
Several nodes stay in "Pending" state

**Environment**
GKE, Nifikop 0.5.2

* Kubernetes version information:
GKE 1.18

* Kubernetes cluster kind: 
Regional GKE cluster

* NiFi version:
irrelevant

**Possible Solution**
Enhance PVC management

**Additional context**
It seems the issue is linked to `PVC` (cluster wide) -> `PV` (zone) mapping. When there are two PVCs defined for the pod, they might be in two different availability zones.

**Comment by d-snyder** [comment]
Is the volume binding mode of the storage class set to "WaitForFirstConsumer"?

**Comment by xvzf** [comment]
Nope and that's a perfect point & will close this issue; I was overcomplicating it a bit :D
