### ISSUE TITLE
Dataflow creation not working

### ISSUE THREAD

**Issue by mertkayhan** [Orange-OpenSource/nifikop#74]
## Type of question

**Are you asking about community best practices, how to implement a specific feature, or about general context and help around nifikop ?**

how to implement a specific feature

## Question

**What did you do?**
Deployed a nifi-registry, nifi cluster, registry client and parameter context. Created a process group and versioned it in nifi-registry. Now I'm trying to deploy a dataflow which references that process group as shown below.

````
apiVersion: nifi.orange.com/v1alpha1
kind: NifiDataflow
metadata:
  name: test
spec:
  parentProcessGroupID: "16cfd2ec-0174-1000-0000-00004b9b35cc"
  bucketId: "2f27bb26-83a4-4b2d-9ed9-78bebdd63c7b"
  flowId: "95f1ed2d-d194-41d0-b844-e5e20df02b3a"
  flowVersion: 1
  runOnce: false
  skipInvalidControllerService: true
  skipInvalidComponent: true
  clusterRef:
    name: nifi
    namespace: ns
  registryClientRef:
    name: nifi-registry-client
    namespace: ns
  parameterContextRef:
    name: dataflow-lifecycle-1
    namespace: ns
  updateStrategy: drain
````

**What did you expect to see?**
I expected to see the process group appear in the ui.

**What did you see instead? Under which circumstances?**

Internal error.

Nifi logs: 

`2021-02-10 12:02:45,936 INFO [NiFi Web Server-132] o.a.n.w.s.NiFiAuthenticationFilter Authentication success for nifi-controller.ns.mgt.cluster.local
2021-02-10 12:02:45,938 INFO [NiFi Web Server-138] o.a.n.w.s.NiFiAuthenticationFilter Attempting request for (CN=nifi-controller.ns.mgt.cluster.local) POST https://nifi-headless.ns.svc.cluster.local:8443/nifi-api/process-groups/eb584e3d-e779-42aa-93bf-9ce5638d0398/process-groups (source ip: x.x.x.x)
2021-02-10 12:02:45,938 INFO [NiFi Web Server-138] o.a.n.w.s.NiFiAuthenticationFilter Authentication success for nifi-controller.ns.mgt.cluster.local
2021-02-10 12:02:45,939 ERROR [NiFi Web Server-138] o.a.nifi.web.api.config.ThrowableMapper An unexpected error has occurred: java.lang.NullPointerException. Returning Internal Server Error response.
java.lang.NullPointerException: null`

Nifikop logs:

`{"level":"info","ts":1612955178.3317182,"logger":"dataflow-method","msg":"Retrieving Nifi client for ns/nifi"}
{"level":"info","ts":1612955178.34934,"logger":"accesspolicies-method","msg":"Retrieving Nifi client for ns/nifi"}
{"level":"error","ts":1612955178.351857,"logger":"nifi_client","msg":"Error during talking to nifi node","error":"Non 201 response from nifi node: 500 Internal Server Error","errorVerbose":"Non 201 response from nifi node: 500 Internal Server Error\ngithub.com/Orange-OpenSource/nifikop/pkg/nificlient.errorCreateOperation\n\tnifikop/pkg/nificlient/common.go:51\ngithub.com/Orange-OpenSource/nifikop/pkg/nificlient.(*nifiClient).CreateProcessGroup\n\tnifikop/pkg/nificlient/processgroup.go:39\ngithub.com/Orange-OpenSource/nifikop/pkg/clientwrappers/dataflow.CreateDataflow\n\tnifikop/pkg/clientwrappers/dataflow/dataflow.go:73\ngithub.com/Orange-OpenSource/nifikop/pkg/controller/nifidataflow.(*ReconcileNifiDataflow).Reconcile\n\tnifikop/pkg/controller/nifidataflow/nifidataflow_controller.go:226\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tnifikop/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:256\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tnifikop/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:232\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\tnifikop/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:211\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\tnifikop/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\tnifikop/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\tnifikop/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.Until\n\tnifikop/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1373","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\tnifikop/vendor/github.com/go-logr/zapr/zapr.go:128\ngithub.com/Orange-OpenSource/nifikop/pkg/nificlient.errorCreateOperation\n\tnifikop/pkg/nificlient/common.go:51\ngithub.com/Orange-OpenSource/nifikop/pkg/nificlient.(*nifiClient).CreateProcessGroup\n\tnifikop/pkg/nificlient/processgroup.go:39\ngithub.com/Orange-OpenSource/nifikop/pkg/clientwrappers/dataflow.CreateDataflow\n\tnifikop/pkg/clientwrappers/dataflow/dataflow.go:73\ngithub.com/Orange-OpenSource/nifikop/pkg/controller/nifidataflow.(*ReconcileNifiDataflow).Reconcile\n\tnifikop/pkg/controller/nifidataflow/nifidataflow_controller.go:226\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tnifikop/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:256\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tnifikop/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:232\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\tnifikop/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:211\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\tnifikop/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\tnifikop/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\tnifikop/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.Until\n\tnifikop/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90"}
{"level":"error","ts":1612955178.3519518,"logger":"dataflow-method","msg":"Create registry-client request failed since Nifi node returned non 201","error":"non 201 response from NiFi cluster","errorVerbose":"non 201 response from NiFi cluster\ngithub.com/Orange-OpenSource/nifikop/pkg/nificlient.init\n\tnifikop/pkg/nificlient/common.go:25\nruntime.doInit\n\t/usr/local/go/src/runtime/proc.go:5420\nruntime.doInit\n\t/usr/local/go/src/runtime/proc.go:5415\nruntime.doInit\n\t/usr/local/go/src/runtime/proc.go:5415\nruntime.doInit\n\t/usr/local/go/src/runtime/proc.go:5415\nruntime.doInit\n\t/usr/local/go/src/runtime/proc.go:5415\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:190\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1373","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\tnifikop/vendor/github.com/go-logr/zapr/zapr.go:128\ngithub.com/Orange-OpenSource/nifikop/pkg/clientwrappers.ErrorCreateOperation\n\tnifikop/pkg/clientwrappers/common.go:35\ngithub.com/Orange-OpenSource/nifikop/pkg/clientwrappers/dataflow.CreateDataflow\n\tnifikop/pkg/clientwrappers/dataflow/dataflow.go:74\ngithub.com/Orange-OpenSource/nifikop/pkg/controller/nifidataflow.(*ReconcileNifiDataflow).Reconcile\n\tnifikop/pkg/controller/nifidataflow/nifidataflow_controller.go:226\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tnifikop/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:256\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tnifikop/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:232\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\tnifikop/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:211\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\tnifikop/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\tnifikop/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\tnifikop/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.Until\n\tnifikop/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90"}
{"level":"error","ts":1612955178.3519928,"logger":"dataflow-method","msg":"could not communicate with nifi node","error":"non 201 response from NiFi cluster","errorVerbose":"non 201 response from NiFi cluster\ngithub.com/Orange-OpenSource/nifikop/pkg/nificlient.init\n\tnifikop/pkg/nificlient/common.go:25\nruntime.doInit\n\t/usr/local/go/src/runtime/proc.go:5420\nruntime.doInit\n\t/usr/local/go/src/runtime/proc.go:5415\nruntime.doInit\n\t/usr/local/go/src/runtime/proc.go:5415\nruntime.doInit\n\t/usr/local/go/src/runtime/proc.go:5415\nruntime.doInit\n\t/usr/local/go/src/runtime/proc.go:5415\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:190\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1373","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\tnifikop/vendor/github.com/go-logr/zapr/zapr.go:128\ngithub.com/Orange-OpenSource/nifikop/pkg/clientwrappers.ErrorCreateOperation\n\tnifikop/pkg/clientwrappers/common.go:39\ngithub.com/Orange-OpenSource/nifikop/pkg/clientwrappers/dataflow.CreateDataflow\n\tnifikop/pkg/clientwrappers/dataflow/dataflow.go:74\ngithub.com/Orange-OpenSource/nifikop/pkg/controller/nifidataflow.(*ReconcileNifiDataflow).Reconcile\n\tnifikop/pkg/controller/nifidataflow/nifidataflow_controller.go:226\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tnifikop/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:256\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tnifikop/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:232\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\tnifikop/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:211\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\tnifikop/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\tnifikop/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\tnifikop/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.Until\n\tnifikop/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90"}
{"level":"info","ts":1612955178.352029,"logger":"controller_nifidataflow","msg":"failure creating dataflow","Request.Namespace":"ns","Request.Name":"test"}
{"level":"error","ts":1612955178.3520458,"logger":"controller-runtime.controller","msg":"Reconciler error","controller":"nifidataflow-controller","request":"ns/test","error":"non 201 response from NiFi cluster","errorVerbose":"non 201 response from NiFi cluster\ngithub.com/Orange-OpenSource/nifikop/pkg/nificlient.init\n\tnifikop/pkg/nificlient/common.go:25\nruntime.doInit\n\t/usr/local/go/src/runtime/proc.go:5420\nruntime.doInit\n\t/usr/local/go/src/runtime/proc.go:5415\nruntime.doInit\n\t/usr/local/go/src/runtime/proc.go:5415\nruntime.doInit\n\t/usr/local/go/src/runtime/proc.go:5415\nruntime.doInit\n\t/usr/local/go/src/runtime/proc.go:5415\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:190\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1373","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\tnifikop/vendor/github.com/go-logr/zapr/zapr.go:128\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tnifikop/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:258\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tnifikop/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:232\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\tnifikop/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:211\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\tnifikop/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\tnifikop/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\tnifikop/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.Until\n\tnifikop/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90"}
{"level":"info","ts":1612955178.3731368,"logger":"controller_nificluster","msg":"CR status updated","Request.Namespace":"ns","Request.Name":"nifi","status":"ClusterRunning"}` 

**Environment**
* nifikop version: 0.4.2 alpha-release

* Kubernetes version information: OpenShift 4.6.z, K8s 1.19

* NiFi version: 1.12.1

**Additional context**
I also got the same error for nifi versions 1.11.4 and 1.13.0.

**Comment by erdrix** [comment]
Any update about this issue ? Have you tried the lastest version of the operator ? (It might help with more debugging info)

**Comment by mertkayhan** [comment]
Hello @erdrix, thanks for the info. I will update the operator and test it again.

**Comment by mertkayhan** [comment]
I was able to narrow down the error to the following:

> dataflow-method	Create registry-client request failed since Nifi node returned non 201

It is not clear to me why the operator tries to create a registry-client and not use the existing one (I already see it in the UI). I have double checked the `registryClientRef` as well.

**Comment by mertkayhan** [comment]
2021-06-14T11:46:06.183Z	INFO	controllers.NifiDataflow	Adding Finalizer for NifiDataflow
E0614 11:46:06.194540       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 762 [running]:

**Comment by mertkayhan** [comment]
Hello @erdrix, I implemented a simple fix for the problem I am facing. I would like to create a PR with my changes. What would be the steps for this?
