### ISSUE TITLE
No initialAdminUser in NifiCluster CRD

### ISSUE THREAD

**Issue by vodwood** [Orange-OpenSource/nifikop#99]
## Bug Report

**What did you do?**
Installed CRD with:
```
kubectl apply -f https://raw.githubusercontent.com/Orange-OpenSource/nifikop/master/config/crd/bases/nifi.orange.com_nificlusters.yaml
kubectl apply -f https://raw.githubusercontent.com/Orange-OpenSource/nifikop/master/config/crd/bases/nifi.orange.com_nifiusers.yaml
kubectl apply -f https://raw.githubusercontent.com/Orange-OpenSource/nifikop/master/config/crd/bases/nifi.orange.com_nifiusergroups.yaml
kubectl apply -f https://raw.githubusercontent.com/Orange-OpenSource/nifikop/master/config/crd/bases/nifi.orange.com_nifidataflows.yaml
kubectl apply -f https://raw.githubusercontent.com/Orange-OpenSource/nifikop/master/config/crd/bases/nifi.orange.com_nifiparametercontexts.yaml
kubectl apply -f https://raw.githubusercontent.com/Orange-OpenSource/nifikop/master/config/crd/bases/nifi.orange.com_nifiregistryclients.yaml
```
And wanted to proceed with secured cluster installation, as per documentation:
https://orange-opensource.github.io/nifikop/docs/3_tasks/2_security/1_ssl

**What did you expect to see?**
Expected the documentation to be up to date.

**What did you see instead? Under which circumstances?**
```kubectl explain nificluster --recursive | grep initialAdminUser``` does not show that the field is present

**Environment**
* nifikop version:

0.6.0-release

**Comment by erdrix** [comment]
Effectively their is an error in this documentation page, since the release 0.4.0 the users are managed following this documentation page : https://orange-opensource.github.io/nifikop/docs/3_tasks/4_nifi_user_group#managed-groups-for-simple-setup
